# Generated by Django 5.1.7 on 2025-03-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_telegramactivationcode_options_and_more'),
        ('users', 'manual_add_telegram_id'),
    ]

    operations = [
    ]
